name: Build

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: D:\nuget\packages

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Test
        run: dotnet test

      - name: Build
        run: dotnet publish RLBotCS -r win-x64

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: RLBotServer-windows
          path: ./**/publish/RLBotServer.exe

  build-linux:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim

    steps:
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y --no-install-recommends clang lld

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Test
        run: dotnet test

      - name: Formatting
        run: |
          dotnet tool restore
          dotnet csharpier check .

      - name: Build
        run: dotnet publish RLBotCS -r linux-x64

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: RLBotServer-ubuntu
          path: ./**/publish/RLBotServer

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [build-linux, build-windows]
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: "true"
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: ./RLBotCS/**/publish/RLBotServer*
          generate_release_notes: true
          body: |
            Pre-built binaries that allows bots to interface with Rocket League via the RLBot v5 spec
